GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMjQ1MjI5NiwiZXhwIjoxNjEyNDUyMzI2fQ.g_mWCtIxjdRWarDAaz0j5Ys__c_Fnhn3GSRQs8bYVgw


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMjQ1MjM5Mn0.Nco52vtCVkQ8BIfzdNYjj-b7FT_CK3UHd-8YRUBcWp4"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMjQ1MjM5Mn0.Nco52vtCVkQ8BIfzdNYjj-b7FT_CK3UHd-8YRUBcWp4"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}